# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: my-app
          image: shashin99/userservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
      imagePullSecrets:
        - name: regcred
