# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-service
  namespace: ds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learner-service
  template:
    metadata:
      labels:
        app: learner-service
    spec:
      containers:
        - name: my-app
          image: shashin99/learnerservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4002
      imagePullSecrets:
        - name: regcred